apiVersion: v1
kind: Secret
type: secrets.kanister.io/azure   
metadata:
  name: "k10-azblob-kasten-bucket-secret"
  namespace: kasten-io     
data:
  azure_storage_account_id: "{{ bucket_name|b64encode }}"
  azure_storage_environment: "{{ azure_storage_env|b64encode }}"
  azure_storage_key: "{{ azure_storage_key|b64encode }}"