apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - kasten-io-mc-namespace.yaml
  - mc-join-configmap.yaml
  - global-azblob-kasten-bucket-secret.yaml
  - global-azblob-kasten-bucket.yaml
  - global-minio-profile.yaml
  - global-minio-secret.yaml
  - global-distribution.yaml
  - policy.yaml
  - transformset.yaml
  - primary-bootstrap.yaml
  - global-policy.yaml
  - join-token-secret.yaml