apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: apps
  namespace: argocd 
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/fullaware/argocd-kasten.git
    path: appsets
    plugin:
      env:
        - name: ENV # prod,stage,test,dev
          value: dev
        - name: DNS
          value: "kasten.fullaware.net"
        - name: EMAIL # kasten.eula.email
          value: "demo@veeam.com"
        - name: COMPANY # kasten.eula.company
          value: "Veeam"
        - name: SOURCE_REPO # spec.source.repoURL
          value: "https://github.com/fullaware/argocd-kasten.git"
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - PruneLast=true
      - CreateNamespace=true
    retry:
      limit: 2
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m0s
        