apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: prod-route53-credentials-secret
  namespace: cert-manager
spec:
  refreshInterval: "15s"
  secretStoreRef:
    name: cluster-secret-store
    kind: ClusterSecretStore
  target:
    name: prod-route53-credentials-secret
  data:
  - secretKey: access-key-id
    remoteRef:
      key: secrets/route53/access-key-id
      property: token
  - secretKey: secret-access-key
    remoteRef:
      key: secrets/route53/secret-access-key
      property: token