apiVersion: config.kio.kasten.io/v1alpha1
kind: Profile
metadata:
  name: "global-azblob-kasten-bucket"
  namespace: kasten-io-mc
  annotations:
spec:
  type: Location
  locationSpec:
    credential:
      secretType: AzStorageAccount
      secret:
        apiVersion: v1
        kind: Secret
        name: "global-azblob-kasten-bucket-secret"
        namespace: kasten-io-mc
    type: ObjectStore
    objectStore:
      name: "kasten-bucket"
      objectStoreType: AZ