apiVersion: v1
kind: ConfigMap
metadata:
  name: mc-join-config
  namespace: kasten-io
  annotations:
    argocd.argoproj.io/hook: PostSync
data:
  cluster-name: primary
  cluster-ingress: <optional cluster ingress>
  primary-ingress: <optional primary ingress override>