apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kasten-app
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: kasten-io
    server: 'https://kubernetes.default.svc'
  source:
    path: aks/kasten-install-token-auth
    repoURL: https://github.com/smohandass/kasten-argocd-k8s.git
    targetRevision: main
    helm:
      valueFiles:
        - values.yaml 
  project: default
  syncPolicy:
    managedNamespaceMetadata:
      labels:
        argocd.argoproj.io/managed-by: argocd
    automated: 
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
