kind: TransformSet
apiVersion: config.kio.kasten.io/v1alpha1
metadata:
  name: transform-storageclass
  namespace: kasten-io
  annotations:
    argocd.argoproj.io/hook: PostSync
    argocd.argoproj.io/sync-wave: "2"
spec:
  comment: |
    Modify the storageClass to change storage tier.
  transforms:
    - subject:
        resource: persistentvolumeclaims
      name: ChangeStorageClass
      json:
        - op: replace
          path: /spec/storageClassName
          value: standard-csi