apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: asteroids-appset
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  generators:
  - clusters:
      selector:
        matchLabels:
          argocd.argoproj.io/secret-type: cluster # Remote clusters only
  template:
    metadata:
      name: 'asteroids-{{name}}'
    spec:
      project: "default"
      source:
        repoURL: https://github.com/fullaware/asteroids.git
        targetRevision: HEAD
        path: kustomize
        kustomize:
          patches:
          - target:
              kind: Ingress
              name: asteroids-app
            patch: |-
              - op: replace
                path: /spec/rules/0/host
                value: {{name}}
      destination:
        server: '{{server}}'
        namespace: asteroids
      syncPolicy:
        managedNamespaceMetadata:
          labels:
            argocd.argoproj.io/managed-by: argocd
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - PruneLast=true
          - CreateNamespace=true
        retry:
          limit: 2
          backoff:
            duration: 5s
            factor: 2
            maxDuration: 3m0s