apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: asteroids-appset
  namespace: argocd
spec:
  generators:
  - clusters: {}
  template:
    metadata:
      name: 'asteroids-{{name}}'
    spec:
      project: "default"
      source:
        repoURL: https://github.com/fullaware/asteroids.git
        targetRevision: HEAD
        path: kustomize
      destination:
        server: '{{server}}'
        namespace: asteroids
      syncPolicy:
        managedNamespaceMetadata:
          labels:
            argocd.argoproj.io/managed-by: argocd
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
