# This example demonstrates the combining of the git generator with a cluster generator
# The expected output would be an application per git directory and a cluster (application_count = git directory * clusters)
#
#
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: kasten-appset
  namespace: argocd
spec:
  generators:
  - clusters:
      selector:
        matchLabels:
          argocd.argoproj.io/secret-type: cluster # Remote clusters only
  template:
    metadata:
      name: 'kasten-io-{{name}}'
    spec:
      project: default 
      sources:
        - repoURL: https://github.com/fullaware/argocd.git
          targetRevision: HEAD
          path: 'apps/kasten-io'
          helm:
            releaseName: k10
        - repoURL: https://github.com/fullaware/argocd.git
          targetRevision: HEAD
          path: 'apps/kasten-io-resources'
      destination:
        server: '{{server}}'
        namespace: 'kasten-io'
      syncPolicy:
        managedNamespaceMetadata:
          labels:
            argocd.argoproj.io/managed-by: argocd
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
